/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes.index'
import { Route as QuizzesSlugRouteImport } from './routes/quizzes.$slug'
import { Route as CoursesCourseIndexRouteImport } from './routes/courses.$course.index'
import { Route as CoursesSubjectIndexRouteImport } from './routes/courses.$subject.index'
import { Route as CoursesSubjectLessonRouteImport } from './routes/courses.$subject.$lesson'
import { Route as CoursesCourseSubjectIndexRouteImport } from './routes/courses.$course.$subject.index'
import { Route as CoursesCourseSubjectLessonRouteImport } from './routes/courses.$course.$subject.$lesson'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesSlugRoute = QuizzesSlugRouteImport.update({
  id: '/quizzes/$slug',
  path: '/quizzes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIndexRoute = CoursesCourseIndexRouteImport.update({
  id: '/courses/$course/',
  path: '/courses/$course/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSubjectIndexRoute = CoursesSubjectIndexRouteImport.update({
  id: '/courses/$subject/',
  path: '/courses/$subject/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSubjectLessonRoute = CoursesSubjectLessonRouteImport.update({
  id: '/courses/$subject/$lesson',
  path: '/courses/$subject/$lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSubjectIndexRoute =
  CoursesCourseSubjectIndexRouteImport.update({
    id: '/courses/$course/$subject/',
    path: '/courses/$course/$subject/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseSubjectLessonRoute =
  CoursesCourseSubjectLessonRouteImport.update({
    id: '/courses/$course/$subject/$lesson',
    path: '/courses/$course/$subject/$lesson',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/courses/$subject/$lesson': typeof CoursesSubjectLessonRoute
  '/courses/$course/': typeof CoursesCourseIndexRoute
  '/courses/$subject/': typeof CoursesSubjectIndexRoute
  '/courses/$course/$subject/$lesson': typeof CoursesCourseSubjectLessonRoute
  '/courses/$course/$subject/': typeof CoursesCourseSubjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/courses/$subject/$lesson': typeof CoursesSubjectLessonRoute
  '/courses/$course': typeof CoursesCourseIndexRoute
  '/courses/$subject': typeof CoursesSubjectIndexRoute
  '/courses/$course/$subject/$lesson': typeof CoursesCourseSubjectLessonRoute
  '/courses/$course/$subject': typeof CoursesCourseSubjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/courses/$subject/$lesson': typeof CoursesSubjectLessonRoute
  '/courses/$course/': typeof CoursesCourseIndexRoute
  '/courses/$subject/': typeof CoursesSubjectIndexRoute
  '/courses/$course/$subject/$lesson': typeof CoursesCourseSubjectLessonRoute
  '/courses/$course/$subject/': typeof CoursesCourseSubjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/stats'
    | '/quizzes/$slug'
    | '/courses/'
    | '/quizzes/'
    | '/courses/$subject/$lesson'
    | '/courses/$course/'
    | '/courses/$subject/'
    | '/courses/$course/$subject/$lesson'
    | '/courses/$course/$subject/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/stats'
    | '/quizzes/$slug'
    | '/courses'
    | '/quizzes'
    | '/courses/$subject/$lesson'
    | '/courses/$course'
    | '/courses/$subject'
    | '/courses/$course/$subject/$lesson'
    | '/courses/$course/$subject'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/leaderboard'
    | '/_authenticated/stats'
    | '/quizzes/$slug'
    | '/courses/'
    | '/quizzes/'
    | '/courses/$subject/$lesson'
    | '/courses/$course/'
    | '/courses/$subject/'
    | '/courses/$course/$subject/$lesson'
    | '/courses/$course/$subject/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  QuizzesSlugRoute: typeof QuizzesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
  CoursesSubjectLessonRoute: typeof CoursesSubjectLessonRoute
  CoursesCourseIndexRoute: typeof CoursesCourseIndexRoute
  CoursesSubjectIndexRoute: typeof CoursesSubjectIndexRoute
  CoursesCourseSubjectLessonRoute: typeof CoursesCourseSubjectLessonRoute
  CoursesCourseSubjectIndexRoute: typeof CoursesCourseSubjectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$slug': {
      id: '/quizzes/$slug'
      path: '/quizzes/$slug'
      fullPath: '/quizzes/$slug'
      preLoaderRoute: typeof QuizzesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$course/': {
      id: '/courses/$course/'
      path: '/courses/$course'
      fullPath: '/courses/$course/'
      preLoaderRoute: typeof CoursesCourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$subject/': {
      id: '/courses/$subject/'
      path: '/courses/$subject'
      fullPath: '/courses/$subject/'
      preLoaderRoute: typeof CoursesSubjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$subject/$lesson': {
      id: '/courses/$subject/$lesson'
      path: '/courses/$subject/$lesson'
      fullPath: '/courses/$subject/$lesson'
      preLoaderRoute: typeof CoursesSubjectLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$course/$subject/': {
      id: '/courses/$course/$subject/'
      path: '/courses/$course/$subject'
      fullPath: '/courses/$course/$subject/'
      preLoaderRoute: typeof CoursesCourseSubjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$course/$subject/$lesson': {
      id: '/courses/$course/$subject/$lesson'
      path: '/courses/$course/$subject/$lesson'
      fullPath: '/courses/$course/$subject/$lesson'
      preLoaderRoute: typeof CoursesCourseSubjectLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  QuizzesSlugRoute: QuizzesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
  CoursesSubjectLessonRoute: CoursesSubjectLessonRoute,
  CoursesCourseIndexRoute: CoursesCourseIndexRoute,
  CoursesSubjectIndexRoute: CoursesSubjectIndexRoute,
  CoursesCourseSubjectLessonRoute: CoursesCourseSubjectLessonRoute,
  CoursesCourseSubjectIndexRoute: CoursesCourseSubjectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
